export { default as FacebookIcon } from './facebook-icon'
export { default as LinkedinIcon } from './linkedin-icon'
export { default as InstagramIcon } from './instagram-icon'
export { default as TiktokIcon } from './tiktok-icon'
export { default as YoutubeIcon } from './youtube-icon'
export { default as GithubIcon } from './github-icon'
export type { SocialMediaIcons } from './icon-types'
