import React from 'react'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import clsx from 'clsx'

import SignOutLayout from '@/features/sign-out-layout/layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = await getMessages()
  const bodyClass = clsx(inter.className, 'bg-background')
  return (
    <html lang={locale}>
      <body className={bodyClass}>
        <NextIntlClientProvider messages={messages}>
          <SignOutLayout>{children}</SignOutLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
