import React from 'react'
import { Lexend_Deca } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import clsx from 'clsx'

import './globals.css'
import { ThemeProvider } from 'flowbite-react'

import DevStockTheme from '@/components/theme'

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['200', '500'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = await getMessages()
  const bodyClass = clsx(lexendDeca.className)
  return (
    <html lang={locale}>
    <ThemeProvider theme={DevStockTheme}>
      <body className={bodyClass}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </ThemeProvider>
    </html>
  )
}
